### ISSUE TITLE
Blog's features

### ISSUE THREAD

**Issue by diessica** [diessica/diessica.github.io#1]
### General
- [x] Highlight current page in navigation
- [ ] External link mark
- [x] Tags
- [ ] Search
- [ ] RSS for tags
- [ ] Newsletter
- [ ] Tables
- [ ] Estimated reading (:exclamation:)
- [ ] Pagination
### In-article
- [ ] Anchor in subtitles
- [x] Footnotes
- [x] Note block
- [ ] Side picture in an article
- [ ] Side figcaption in an article
- [ ] Share buttons
- [x] Related posts to an article
- [ ] Emojis
### Tech
- [ ] EJS to nunjucks
- [x] Sass to PostCSS
## 

:exclamation:  _Not sure whether it is going to be implemented yet._

**Comment by simaodeveloper** [comment]
Why not Nunjucks instead of dot ?

**Comment by diessica** [comment]
Because of its simplicity and good performance.

But I just noticed that Hexo 3 uses Nunjucks for rendering **by default**, so I've changed my mind. 

Thank you very much!
