### ISSUE TITLE
[Discussion] Computer and Human Languages

### ISSUE THREAD

**Issue by cassmtnr** [diessica/diessica.github.io#7]
> About https://diessi.ca/blog/computer-and-human-languages/

You should definitively publish this on Medium to a bigger viewing range, it's a very interesting, enriching and inspiring text. Thank you for that!

**Comment by diessica** [comment]
Thank you for the kind words. I appreciate the suggestion but I'm not very fond of Medium.

If you like it feel free to share with others!
